user-message: "WARNING: This stack project is generated."

resolver: lts-18.28

# We have 14 packages.
packages:
  - ./yesod
  - ./yesod-auth
  - ./yesod-auth-oauth
  - ./yesod-bin
  - ./yesod-core
  - ./yesod-eventsource
  - ./yesod-form
  - ./yesod-form-multi
  - ./yesod-newsfeed
  - ./yesod-persistent
  - ./yesod-sitemap
  - ./yesod-static
  - ./yesod-test
  - ./yesod-websockets

extra-deps:
  # Package versions for published packages either not on Stackage or
  # not matching the version on Stackage for the resolver we use.
  # These package-version extra dependencies are equivalent to cabal constraints.
  - attoparsec-aeson-2.1.0.0
