[ "yesod"
, "yesod-auth"
, "yesod-auth-oauth"
, "yesod-bin"
, "yesod-core"
, "yesod-eventsource"
, "yesod-form"
, "yesod-form-multi"
, "yesod-newsfeed"
, "yesod-persistent"
, "yesod-sitemap"
, "yesod-static"
, "yesod-test"
, "yesod-websockets"
]
